### ISSUE TITLE
Using a pressure plate while opening a castle gates is broken

### ISSUE THREAD

**Issue by searedOG** [DevotedMC/CastleGates#16]
I'm not on the /nl group, but when I stand on the pressure plate the redstone activates, which activates the castle gates. 

http://imgur.com/a/n0izc

First Image: Before me standing on the pressure plate.

Second Image: After me standing on the pressure plate.

**Comment by ProgrammerDan** [comment]
fwiw I confirmed he isn't on the group.

**Comment by Aleksey-Terzi** [comment]
@ProgrammerDan
Could you please provide castlegates config? (I don't need list of blocks if it is considered as not-for-players info)

@searedOG
Could you please confirm that gearblocks do not belong to your groups as well?

CastleGates is checking /nl groups only for blocks which are currently in the world.
This means that if you haven't access to "bridge" blocks but have access to gearblocks - it could close gates (because of "bridge" blocks are hidden at the moment) but cannot open.

**Comment by ProgrammerDan** [comment]
I don't think the gears were reinforced, just the pressure plate ... I'd have to doublecheck

**Comment by ProgrammerDan** [comment]
@Aleksey-Terzi 

Config:

```
Settings:
  AllowAutoCreate: true
  MaxPowerTransfers: 8
  MaxBridgeLength: 16
  PlayerStateResetInSeconds: 300
  SwitchTimeout: 1000
  MaxRedstoneDistance: 7
  InteractWithSnitches: true
  LogChanges: true
```
